# Generated by Django 2.2.1 on 2019-10-14 00:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=60)),
                ('category', models.CharField(choices=[('Financial Goals', 'Financial Goals'), ('Relationship Goals', 'Relationship Goals'), ('Physical Goals', 'Physical Goals'), ('Career Goals', 'Career Goals'), ('Spiritual Goals', 'Spiritual Goals'), ('Family/Friendship Goals', 'Family/Friendship Goals'), ('Philanthropic Goals', 'Philanthropic Goals')], default='Financial Goals', max_length=23)),
            ],
        ),
        migrations.CreateModel(
            name='GoalDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('focus_level', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('motivation', models.CharField(choices=[('low', 'low'), ('med', 'medium'), ('high', 'high')], default='med', max_length=6)),
                ('time_line', models.DateField()),
                ('goal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Goals')),
            ],
        ),
    ]
