# Generated by Django 2.2.6 on 2020-02-02 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
