# Generated by Django 3.0.3 on 2020-02-21 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_delete_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='time_line',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
