# Generated by Django 3.0.3 on 2020-02-24 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_goals_time_line'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goals',
            old_name='time_line',
            new_name='date',
        ),
    ]
