# Generated by Django 3.0.3 on 2020-03-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20200226_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='goaldetail',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='Not Started', max_length=23),
        ),
    ]
