# Generated by Django 3.0.3 on 2020-03-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_goaldetail_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.PositiveIntegerField()),
            ],
        ),
    ]
