# Generated by Django 2.2.6 on 2020-04-04 03:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('No activo', 'No activo')], default='Activo', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('No activo', 'No activo')], default='Activo', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadVendida', models.PositiveIntegerField()),
                ('precioVenta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fec_creacion', models.DateField(default=datetime.date.today)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Cliente')),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Departamento')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('cedula', models.CharField(max_length=25)),
                ('direccion', models.CharField(max_length=60)),
                ('fec_creacion', models.DateField(default=datetime.date.today)),
                ('usuario', models.CharField(max_length=60)),
                ('correo', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('fec_elaboracion', models.DateField()),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('fec_vencimiento', models.DateField()),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('No activo', 'No activo')], default='Activo', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('No activo', 'No activo')], default='Activo', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_telefono', models.CharField(max_length=20)),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Tipoproducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Tipotelefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='goaldetail',
            name='goal_id',
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
        migrations.DeleteModel(
            name='GoalDetail',
        ),
        migrations.DeleteModel(
            name='Goals',
        ),
        migrations.AddField(
            model_name='telefono',
            name='id_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Tipotelefono'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Tipoproducto'),
        ),
        migrations.AddField(
            model_name='factura',
            name='id_sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Sucursal'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='id_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Persona'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='id_sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Sucursal'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='id_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Empleado'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='id_factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Factura'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Producto'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Persona'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='id_departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Departamento'),
        ),
    ]
