# Generated by Django 2.2.6 on 2020-04-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_auto_20200403_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='id_producto',
            new_name='id_tipo_producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
