# Generated by Django 2.2.6 on 2020-04-22 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_auto_20200422_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fec_compra',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
