# Generated by Django 2.2.6 on 2020-04-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_producto_fec_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='id_persona',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='descripcion',
            field=models.CharField(default='Rica', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(default='809-225-5656', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(default='Avenida Duarte, esquina SASASAS', max_length=60),
            preserve_default=False,
        ),
    ]
