# Generated by Django 2.2.6 on 2020-04-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_auto_20200423_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
